### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/mimir#1]
I'll outline the roadmap here.

- [ ] Merge all information and ideas from [data myr](https://github.com/MrHedmad/data-myr.git) into mimir;
- [ ] Define an ontology for types of samples, output files and formats.
- [ ] Define how to package data for export. For instance, a .zip file with associated metadata file (in some format).
- [ ] Define overall workflow, from idealization to data upload;
- [ ] Define strategies to implement the workflow;
